# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.x

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Build Windows
      env:
        GOOS: windows
        GOARCH: amd64
      run: | 
        VERSION="$(git describe --tags)_DEV"
        go build -v -trimpath -ldflags "-w -s -X main.Version=$VERSION" -o fairy-tale-generator.exe .


    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        path: fairy-tale-generator.exe       